[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
# Esto instala Babel y compila tus archivos de src a una carpeta 'dist'
cmds = [
    "npm install --save-dev @babel/core @babel/cli @babel/preset-react",
    "npx babel src --out-dir dist"
]

[start]
# Ahora servimos la carpeta 'dist' donde ya está tu código convertido a JS puro
cmd = "npx serve -s dist"